image: gitpod/workspace-dotnet

ports:
  - port: 5000

tasks:
  - init: gp env ASPNETCORE_URLS="http://+:5000"
  - init: dotnet restore KitchenService
  - command: dotnet run -p KitchenService/KitchenService.Api

vscode:
  extensions:
    - ms-vscode.csharp@1.21.12:kw8SkO8+aVTSFug281WfQQ==
