image: gitpod/workspace-dotnet

ports:
  - port: 5000
    onOpen: open-browser
  - port: 5001
    onOpen: open-browser

tasks:
  - init: dotnet restore KitchenService
  - command: dotnet run -p KitchenService/KitchenService.Api

vscode:
  extensions:
    - ms-vscode.csharp@1.21.12:kw8SkO8+aVTSFug281WfQQ==
