image:
  file: .gitpod.Dockerfile

ports:
  - port: 5000
    onOpen: open-preview
  - port: 5001
    onOpen: open-preview

tasks:
  - init: dotnet restore KitchenService
  - command: dotnet run -p KitchenService/KitchenService.Api

vscode:
  extensions:
    - ms-vscode.csharp@1.21.12:kw8SkO8+aVTSFug281WfQQ==
